baseURL: "https://relentlessoptimizer.com"
title: "Relentless Optimizer"
paginate: 10
# 'Relentless' is a minimal theme from scratch.
# 'PaperModMe' is my customizations on the PaperMod theme.
#theme: "relentless"
theme: "PaperModMe"
pluralizeListTitles: false  # To auto convert list titles 'Gamings'
summaryLength: 20
LanguageCode: en

enableInlineShortcodes: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: true
buildExpired: false

# googleAnalytics: UA-123-45
#disableLiveReload: true    # Or hugo server --watch=false
#canonifyURLs: true         # To make all URLs absolute

minify:
    #disableCSS: true        # Don't minify CSS (easier to debug)
    disableXML: true
    #minifyOutput: true

permalinks:
  gaming:  gaming/:year/:month/:day/:title/
  code:    code/:year/:month/:day/:title/
  finance: finance/:year/:month/:day/:title/

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About
                  url: about
                  weight: 5
                - name: Code
                  url: code/
                  weight: 10
                - name: Finance
                  url: finance/
                  weight: 10
                - name: Gaming
                  url: gaming/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    mainSections:
        - gaming
        - code
        - finance
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Incessantly optimizing code, games, and finances."
    disableScrollToTop: true
    disableMenuScroll: true
    disableThemeToggle: false
    summaryLength: 60

    defaultTheme: auto
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    #ShowToc: true
    #comments: false
    #images: ["papermod-cover.png"]

    socialIcons:
        - name: RSS
          url: "index.xml"
        - name: email
          url: "mailto:scottlo@outlook.com"
        - name: github
          url: "https://github.com/ScottLouvau"
        - name: LinkedIn
          url: "https://linkedin.com/in/scott-louvau-97846531"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

# Static Code Highlighting via Chroma
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
     # anchorLineNos: true
     codeFences: true
     guessSyntax: true
     lineNos: false
     noClasses: false
     style: monokai

# Privacy + GDPR
privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true